workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk
    scripts:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
